[login]
username = 
password = 


; 예시
; srt = SRT("1234567890", YOUR_PASSWORD) # with membership number
; srt = SRT("def6488@gmail.com", YOUR_PASSWORD) # with email
; srt = SRT("010-1234-xxxx", YOUR_PASSWORD) # with phone number

[reservation]
date = 20240914
time = 140000
time_limit = 180000
departure = 수서
destination = 동대구
train_kind = SRT


[discord]
